name: movieapp
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  dio: ^5.8.0+1
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  image_network: ^2.6.0
  chewie: ^1.10.0
  video_player: ^2.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

